chore: code formatting

diff --git a/.s1n7ax/common/bin/dir-bookmarks b/.s1n7ax/common/bin/dir-bookmarks
--- a/.s1n7ax/common/bin/dir-bookmarks
+++ b/.s1n7ax/common/bin/dir-bookmarks
@@ -1,34 +1,34 @@
 #!/bin/env bash
 
-sub_help(){
-    echo "Usage: $ProgName <subcommand> [options]\n"
-    echo "Subcommands:"
-    echo "    save"
-    echo "    list"
-    echo ""
+sub_help() {
+	echo "Usage: $ProgName <subcommand> [options]\n"
+	echo "Subcommands:"
+	echo "    save"
+	echo "    list"
+	echo ""
 }
 
 sub_save() {
-    bookmarks --config ~/.cache/project/list save "$(pwd)"
+	bookmarks --config ~/.cache/project/list save "$(pwd)"
 }
 
 sub_list() {
-    bookmarks --config ~/.cache/project/list list
+	bookmarks --config ~/.cache/project/list list
 }
 
 subcommand=$1
 
 case $subcommand in
-    "" | "-h" | "--help")
-        sub_help
-        ;;
-    *)
-        shift
-        sub_${subcommand} $@
-        if [ $? = 127 ]; then
-            echo "Error: '$subcommand' is not a known subcommand." >&2
-            echo "       Run '$ProgName --help' for a list of known subcommands." >&2
-            exit 1
-        fi
-        ;;
+"" | "-h" | "--help")
+	sub_help
+	;;
+*)
+	shift
+	sub_${subcommand} $@
+	if [ $? = 127 ]; then
+		echo "Error: '$subcommand' is not a known subcommand." >&2
+		echo "       Run '$ProgName --help' for a list of known subcommands." >&2
+		exit 1
+	fi
+	;;
 esac
