feat: update config

diff --git a/.s1n7ax/common/bin/mkv-to-mov b/.s1n7ax/common/bin/mkv-to-mov
--- a/.s1n7ax/common/bin/mkv-to-mov
+++ b/.s1n7ax/common/bin/mkv-to-mov
@@ -1,24 +1,39 @@
-#!/bin/bash
+#!/bin/sh
 
 set -euxo pipefail
 
 
 if [[ $# -eq 0 ]] ; then
-    echo 'Converting all the files in the current dir to mov'
+  # has no parameters
+  echo 'Converting all the files in the current dir to mov'
 
-    ls *.mkv | \
+  mov_files=$(fd -t f --no-ignore '.*\.mkv')
+
+  if [ -n "$mov_files" ]; then
+    mkdir -p "converted";
+    
+    echo "$mov_files" | 
     xargs -I {} basename {} .mkv | \
     xargs -I {} \
-    sh -c 'ffmpeg -i "{}.mkv" -vcodec mjpeg -q:v 2 -acodec pcm_s16be -q:a 0 -f mov "{}.mov"'
+    sh -c 'ffmpeg -i "{}.mkv" -vcodec mjpeg -q:v 2 -acodec pcm_s16be -q:a 0 -f mov "converted/{}.mov"'
+  fi
 
-    exit 0
-  else
-    echo 'Converting "$1" to mov'
+  exit 0
+else
+  echo 'Converting "$1" to mov'
 
-    ABSOLUTE_PATH=$(realpath "$1")
-    FILE_PATH_WITHOUT_EXT="${ABSOLUTE_PATH%%.*}"
-    TARGET_PATH="$FILE_PATH_WITHOUT_EXT.mov"
+  abs_path=$(realpath "$1")
 
-    exit 0
+  if [ ! -f "$abs_path" ]; then
+    echo "File not found"
+    exit 1;
+  fi
+
+  mkdir -p "converted"
+  target="$(dirname "$abs_path")/converted/$(basename "$abs_path")"
+
+  ffmpeg -i "$abs_path" -vcodec mjpeg -q:v 2 -acodec pcm_s16be -q:a 0 -f mov "$target_path"
+
+  exit 0
 fi
 
